apiVersion: v2
name: headmaster
description: Kubernetes operator for the headscale control plane
type: application
version: 0.1.0 # x-release-please-version
appVersion: "0.1.0" # x-release-please-version
icon: https://raw.githubusercontent.com/juanfont/headscale/main/docs/logo/headscale3.svg
