{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headmaster.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headmaster.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "headmaster.selectorLabels" . | nindent 4 }}
  ports:
    - port: 443
      targetPort: 9443
      name: webhook
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "headmaster.fullname" . }}-selfsigned
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headmaster.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "headmaster.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headmaster.labels" . | nindent 4 }}
spec:
  secretName: {{ include "headmaster.fullname" . }}-webhook-tls
  dnsNames:
    - {{ include "headmaster.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "headmaster.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "headmaster.fullname" . }}-selfsigned
    kind: Issuer
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "headmaster.fullname" . }}
  labels:
    {{- include "headmaster.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "headmaster.fullname" . }}-webhook
webhooks:
  - name: validate.headscaleinstances.headmaster.potatonode.github.io
    rules:
      - apiGroups: [headmaster.potatonode.github.io]
        apiVersions: [v1alpha1]
        resources: [headscaleinstances]
        operations: [CREATE, UPDATE]
    clientConfig:
      service:
        name: {{ include "headmaster.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        port: 443
        path: /validate
    failurePolicy: Fail
    admissionReviewVersions: [v1]
    sideEffects: None
    timeoutSeconds: 30
{{- end }}
