apiVersion: v2
name: headmaster-examples
description: Example headmaster resources for a single-instance headscale deployment
version: 0.1.0
dependencies:
  - name: headmaster
    version: "0.2.0"
    repository: "file://../chart"
  - name: pocket-id-operator
    version: "0.7.1"
    repository: oci://ghcr.io/aclerici38/charts
